# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Generate Lists
      run: |
        python3 generate_lists.py
    - name: Update Lists
      run: |
        git config --global user.name "Mikrotik AdGuardHome"
        git config --global user.email "bot@github.io"
        git add .
        git commit -m "Update $(date '+%Y-%m-%d')"
        git push
